export const GET_USER_REPO = 'GET USER REPO'
export const GET_USER_REPO_SUCCESS = 'GET USER REPO SUCCESS'
export const GET_USER_REPO_FAILED = 'GET USER REPO FAILED'
export const REFRESH_STATE = 'REFRESH STATE'